### ISSUE TITLE
suzuriのステッカーに対応させたい

### ISSUE THREAD

**Issue by ikatake** [ikatake/lifegamebotpage#12]
https://note.mu/suzurijp/n/ne8dea05458c3
https://note.mu/suzurijp/n/n1a50dc180442

とりあえずイシューあげます。

**Comment by detcoder** [comment]
使用フォントの指定はありますか？

**Comment by ikatake** [comment]
ステッカーは状態のみを画像にしたいと思います。
したがって、文字は不要とします。

**Comment by detcoder** [comment]
了解です。タイルな絵のみですね。
それでしたら現在のmakePNGを再設定、の手法もあり得るかと。

**Comment by ikatake** [comment]
issueあげたの忘れてた。閉じます。
