### ISSUE TITLE
初期表示で再生ボタンを押しても何も走らないのが寂しい

### ISSUE THREAD

**Issue by ikatake** [ikatake/lifegamebotpage#7]
繰返しPBかループPBをデフォルトでONしておけばよいのでは

**Comment by ikatake** [comment]
初期の表示で、Repeatを「現在のgeneを繰り返す」にすることとしたく。
 シャッフルはOFFのまま。　∵いきなりランダムに飛ぶのは違和感があると思う。
→stepの浅いgeneだとあまり変化がないのが苦しいところ。

**Comment by detcoder** [comment]
ナイスな解決案だと思います。同意。

**Comment by ikatake** [comment]
マスタに反映済みなので、これにて閉じます。
